Basic structure of the new website
TheAlgorithms/website-old pull request #25
Opened 2018-10-28 04:11 UTC by feralCode

### react + babel + webpack added.
webpack dev server can be started with `yarn start` command
sass added for styling, more work to be done but didn't want to make PR to large. 
Original styling left in Main component in src directory

![screenshot_2018-10-28_00-09-22](https://user-images.githubusercontent.com/602559/47611930-00c0c780-da46-11e8-82b5-1861e0b6cabe.png)

#23

2018-10-28 05:13 UTC, AnshulMalik commented
Nice work @feralCode 

I think we don't need yarn error log

2018-12-18 14:52 UTC, AnshulMalik requested changes
So sorry this was ignored for so long, we can now go fast track. :)

2018-12-18 14:52 UTC, AnshulMalik commented on package.json
> +  "repository": "https://github.com/feralCode/website",
we should use the upstream repository here.

2018-12-18 14:52 UTC, AnshulMalik commented on src/scripts/Main.jsx
> +              >
what's going on here?

2018-12-18 14:52 UTC, AnshulMalik commented on src/scripts/Main.jsx
> +        <footer>
I think this file needs formatting.

2018-12-18 14:52 UTC, AnshulMalik commented on src/styles/index.scss
> + //background: linear-gradient(135deg,  #ffded1 0%,#ffded1 50%,#ffc5af 50%,#ffc5af 100%); /* W3C */
comments? I think we don't need them.

2018-12-18 14:52 UTC, AnshulMalik commented on src/scripts/Components/Hero/index.jsx
> +          <img className="bg-image" src="https://images.unsplash.com/photo-1527234639945-70d78416bd7d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=721783d6df00ea979608158fd776675e&auto=format&fit=crop&
I think we'll be fine without this image for now.

2018-12-18 14:52 UTC, AnshulMalik commented on src/scripts/Components/Header/index.jsx
> +      profileImageURL: 'https://d1r8m46oob3o9u.cloudfront.net/images/home-demo-photo-0c.jpg',
let's not have any images.

2019-01-18 12:39 UTC, AnshulMalik commented
@feralCode any updates on this?

2019-02-14 20:39 UTC, christianbender commented
@AnshulMalik The last reaction was 27 days ago. Should we close the pull request?

2019-02-15 11:42 UTC, closed without merging